### ISSUE TITLE
Restaurants (Home) Page Implementation

### ISSUE THREAD

**Issue by shortxmas** [manoa-bites/manoa-bites#1]
**Create a issue associated branch using the development branch function prefixing the branch name with your last name eg. miguel-11-update-food-crud-functionality**

Home page must do the following : 
1. Display all restaurants with search, filter (by restaurant tags) and sort functionalities
2. User favorite button that saves the restaurant to Users favorites if logged in -- popup a signup if not logged in

**Comment by pelitaf** [comment]
Once restaurant cards are implemented. It should be fairly easy to render the cards just like we did for digits contacts.
