### ISSUE TITLE
Issue Form Page

### ISSUE THREAD

**Issue by shortxmas** [manoa-bites/manoa-bites#10]
**Create a issue associated branch using the development branch function prefixing the branch name with your last name eg. miguel-11-update-food-crud-functionality**

Within the footer of the app, there will be a link to go to a page to submit an issue with the website.
Implement this page using form input fields like name, email, issue and use a form submission API like [FormSubmit](https://formsubmit.co/)

**Comment by pelitaf** [comment]
Issue Form pops up when I use npm run dev and run it locally. Doesn't work for me on vercel.

**Comment by pelitaf** [comment]
Should be simple. Can copy steps used for "Add Stuff" in template.
