### ISSUE TITLE
Dynamic Grabbing of Restaurant Pins

### ISSUE THREAD

**Issue by pelitaf** [manoa-bites/manoa-bites#52]
do this work in a branch called issue-52

update map makers on google maps API to include restaurants added
*possibly add search bar in googlemap?*

Fetch all restaurant data upon page load and then populate pins using restaurant data latitude and longitude

**Comment by johnbernardo2** [comment]
Likely going to take longer as im implementing a higher complexity of a task, so my estimate is 6 hours, 2 for research
