### ISSUE TITLE
(JIC) Implement Search, Filter and Sort Functions on Home Page Directory

### ISSUE THREAD

**Issue by shortxmas** [manoa-bites/manoa-bites#57]
**Create a issue associated branch using the development branch function prefixing the branch name with your last name eg. miguel-11-update-food-crud-functionality**

**Comment by pelitaf** [comment]
Haven't done anything of this complexity so will be challenging.

**Comment by pelitaf** [comment]
Implementation done, just need to update locationNames to correspond with locationId
