### ISSUE TITLE
Individual Restaurant Page Design

### ISSUE THREAD

**Issue by shortxmas** [manoa-bites/manoa-bites#61]
**Create a issue associated branch using the development branch function prefixing the branch name with your last name eg. miguel-11-update-food-crud-functionality**

functionality on /restaurant/[restaurantId] works for fetching the restaurant object, just need to make the page look pretty (i'm bad at design)

**Comment by pelitaf** [comment]
I love front-end UI so this should be quick, unless I start getting really picky about format
